export const AP_SUBJECTS = [
  "Art History",
  "Biology",
  "Calculus AB",
  "Calculus BC",
  "Chemistry",
  "Computer Science A",
  "English Language",
  "English Literature",
  "Environmental Science",
  "European History",
  "Macroeconomics",
  "Microeconomics",
  "Physics 1",
  "Physics C: Mechanics",
  "Psychology",
  "Statistics",
  "US Government",
  "US History",
  "World History",
];
